// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdnbtjplzbatowzbxqis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkbmJ0anBsemJhdG93emJ4cWlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA1MDgxNjYsImV4cCI6MjEwNjA4NDE2Nn0.o9Y7ZywnVYFWQXevCUQRd-cCCbg1kspD2J4Vhu2KVLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});